param(
    [Parameter(Mandatory = $true)]
    [string]$OutputFile
)

$t = [DateTime]::UtcNow.Ticks
$v3 = (([int]($t % 65535)) + 65535) % 65535
$q = [Math]::Floor([decimal]$t / 65535)
$v4 = (([int]($q % 65535)) + 65535) % 65535

$dir = Split-Path -Parent $OutputFile
if (-not [string]::IsNullOrWhiteSpace($dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

$content = @(
    'using System.Reflection;',
    '// Generated by WriteWorkersAssemblyVersion.ps1 - do not edit.',
    "[assembly: AssemblyVersion(`"1.0.$v3.$v4`")]"
)
Set-Content -LiteralPath $OutputFile -Encoding utf8 -Value $content
